spring:
  datasource:
    url: jdbc:h2:/Users/hyia/Project/config
    driver-class-name: org.h2.Driver
    username: hyia
    password: 0622
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    